# Generated by Django 4.0.6 on 2022-07-20 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'News'},
        ),
        migrations.AddField(
            model_name='news',
            name='is_top',
            field=models.BooleanField(default=False),
        ),
    ]
